apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - name: "vote-result"
      port: 81
      targetPort: 80
      nodePort: 31001
     